apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-deploy
      app:  demo-voting-app
  template:
    metadata: 
      name: postgres-deploy
      labels:
        name: postgres-deploy
        app: demo-voting-app
    spec:
      containers:
        - name: postgres-deploy
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"

