apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-deploy
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-deploy
      labels:
        name: voting-app-deploy
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: docker/example-voting-app-vote:latest
          ports:
            - containerPort: 80