apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-deploy
      app: demo-voting-app
  template:
    metadata:
      name: worker-deploy
      labels:
        name: worker-deploy
        app: demo-voting-app
    spec:
      containers:
        - name: worker-deploy
          image: docker/example-voting-app-worker:latest

